# Default initial positions for dual_fr3's ros2_control fake system

initial_positions:
  left_fr3_finger_joint1: 0
  left_fr3_joint1: 0
  left_fr3_joint2: -0.785
  left_fr3_joint3: 0
  left_fr3_joint4: -2.356
  left_fr3_joint5: 0
  left_fr3_joint6: 1.571
  left_fr3_joint7: 0.785
  right_fr3_finger_joint1: 0
  right_fr3_joint1: 0
  right_fr3_joint2: -0.785
  right_fr3_joint3: 0
  right_fr3_joint4: -2.356
  right_fr3_joint5: 0
  right_fr3_joint6: 1.571
  right_fr3_joint7: 0.785