# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    right_fr3_hand_controller:
      type: position_controllers/GripperActionController


    left_fr3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_fr3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_fr3_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

franka_robot_state_broadcaster:
  ros__parameters:
    lock_try_count: 5
    lock_sleep_interval: 5
    lock_log_error: false
    lock_update_success: true

right_fr3_hand_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    joint: right_fr3_finger_joint1

left_fr3_arm_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_joint7
    gains:
        left_fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        left_fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        left_fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        left_fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        left_fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        left_fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        left_fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

right_fr3_arm_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_joint7
    gains:
        right_fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        right_fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        right_fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        right_fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        right_fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        right_fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        right_fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

left_fr3_hand_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    joint: left_fr3_finger_joint1
